image:
  name: maven:3.9-eclipse-temurin-17
  entrypoint: [""]

services:
  - name: container-registry.oracle.com/database/express:21.3.0-xe
    alias: oracle

stages:
  - build
  - reset-db
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DB_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
  DB_USERNAME: SAE3A01
  DB_PASSWORD: $iutinfo

build:
  stage: build
  script:
    - echo "Starting the Maven build..."
    - mvn clean package -B
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

reset-db:
  stage: reset-db
  script:
    - echo "Resetting the database..."
    - mvn exec:java -Dexec.mainClass="dao.CreateBD"
    - mvn exec:java -Dexec.mainClass="dao.InputData"

test:
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test -B
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    expire_in: 1 week

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying the application..."
    - echo "Deployment complete."