stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    - ./build.sh

test:
  stage: test
  script:
    - echo "Running tests..."
    - ./test.sh

deploy:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - ./deploy.sh
