stages:
  - build
  - test
  - deploy

# Define a Maven build stage
build:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "Building the project..."
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    when: always

# Define a Maven test stage
test:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "Running tests..."
    - mvn test

# Optional deployment stage (can be customized later)
deploy:
  stage: deploy
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "Deploying the project..."
    - echo "No deployment configured yet!"
